// Code generated by "stringer -output opcode_string.go -type OpCode"; DO NOT EDIT.

package compiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpConstant-0]
	_ = x[OpNil-1]
	_ = x[OpCall-2]
	_ = x[OpReturn-3]
	_ = x[OpGetLocal-4]
	_ = x[OpGetUpvalue-5]
	_ = x[OpGetGlobal-6]
	_ = x[OpSetLocal-7]
	_ = x[OpSetGlobal-8]
	_ = x[OpClosure-9]
	_ = x[OpCloseUpvalue-10]
	_ = x[OpPop-11]
}

const _OpCode_name = "OpConstantOpNilOpCallOpReturnOpGetLocalOpGetUpvalueOpGetGlobalOpSetLocalOpSetGlobalOpClosureOpCloseUpvalueOpPop"

var _OpCode_index = [...]uint8{0, 10, 15, 21, 29, 39, 51, 62, 72, 83, 92, 106, 111}

func (i OpCode) String() string {
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
