// Code generated by "stringer -output opcode_string.go -type OpCode"; DO NOT EDIT.

package compiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpConstant-0]
	_ = x[OpNil-1]
	_ = x[OpCall-2]
	_ = x[OpTailCall-3]
	_ = x[OpCallBuiltin-4]
	_ = x[OpReturn-5]
	_ = x[OpGetLocal-6]
	_ = x[OpSetLocal-7]
	_ = x[OpGetUpvalue-8]
	_ = x[OpSetUpvalue-9]
	_ = x[OpGetGlobal-10]
	_ = x[OpDefineGlobal-11]
	_ = x[OpSetGlobal-12]
	_ = x[OpClosure-13]
	_ = x[OpPop-14]
	_ = x[OpJump-15]
	_ = x[OpJumpIfFalse-16]
	_ = x[OpJumpIfTrue-17]
}

const _OpCode_name = "OpConstantOpNilOpCallOpTailCallOpCallBuiltinOpReturnOpGetLocalOpSetLocalOpGetUpvalueOpSetUpvalueOpGetGlobalOpDefineGlobalOpSetGlobalOpClosureOpPopOpJumpOpJumpIfFalseOpJumpIfTrue"

var _OpCode_index = [...]uint8{0, 10, 15, 21, 31, 44, 52, 62, 72, 84, 96, 107, 121, 132, 141, 146, 152, 165, 177}

func (i OpCode) String() string {
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
