// Code generated by "stringer -output opcode_string.go -type OpCode"; DO NOT EDIT.

package compiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpConstant-0]
	_ = x[OpNil-1]
	_ = x[OpCall-2]
	_ = x[OpTailCall-3]
	_ = x[OpReturn-4]
	_ = x[OpGetLocal-5]
	_ = x[OpSetLocal-6]
	_ = x[OpGetUpvalue-7]
	_ = x[OpSetUpvalue-8]
	_ = x[OpGetGlobal-9]
	_ = x[OpDefineGlobal-10]
	_ = x[OpSetGlobal-11]
	_ = x[OpClosure-12]
	_ = x[OpPop-13]
	_ = x[OpJump-14]
	_ = x[OpJumpIfFalse-15]
	_ = x[OpJumpIfTrue-16]
}

const _OpCode_name = "OpConstantOpNilOpCallOpTailCallOpReturnOpGetLocalOpSetLocalOpGetUpvalueOpSetUpvalueOpGetGlobalOpDefineGlobalOpSetGlobalOpClosureOpPopOpJumpOpJumpIfFalseOpJumpIfTrue"

var _OpCode_index = [...]uint8{0, 10, 15, 21, 31, 39, 49, 59, 71, 83, 94, 108, 119, 128, 133, 139, 152, 164}

func (i OpCode) String() string {
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
