// Code generated by "stringer -output token_string.go -type TokenType"; DO NOT EDIT.

package tokenizer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenErr-1]
	_ = x[TokenLeftParen-2]
	_ = x[TokenRightParen-3]
	_ = x[TokenDot-4]
	_ = x[TokenQuote-5]
	_ = x[TokenBackquote-6]
	_ = x[TokenComma-7]
	_ = x[TokenNumber-8]
	_ = x[TokenAtom-9]
}

const _TokenType_name = "TokenEOFTokenErrTokenLeftParenTokenRightParenTokenDotTokenQuoteTokenBackquoteTokenCommaTokenNumberTokenAtom"

var _TokenType_index = [...]uint8{0, 8, 16, 30, 45, 53, 63, 77, 87, 98, 107}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
