// Code generated by "stringer -output token_string.go -type tokenType"; DO NOT EDIT.

package glisp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenEOF-0]
	_ = x[tokenErr-1]
	_ = x[tokenLeftParen-2]
	_ = x[tokenRightParen-3]
	_ = x[tokenDot-4]
	_ = x[tokenQuote-5]
	_ = x[tokenNumber-6]
	_ = x[tokenAtom-7]
}

const _tokenType_name = "tokenEOFtokenErrtokenLeftParentokenRightParentokenDottokenQuotetokenNumbertokenAtom"

var _tokenType_index = [...]uint8{0, 8, 16, 30, 45, 53, 63, 74, 83}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
